#!/usr/bin/env node
/**
 * Seed script to populate schools data
 * Run with: node scripts/seed-schools.mjs
 */

import { createConnection } from 'mysql2/promise';
import dotenv from 'dotenv';

dotenv.config();

const schools = [
  // 小學 - 九龍城區
  {
    name: "喇沙小學",
    nameEn: "La Salle Primary School",
    type: "primary",
    category: "aided",
    gender: "boys",
    religion: "catholic",
    district: "九龍城區",
    address: "九龍喇沙利道1D",
    phone: "23366989",
    email: "info@lasalle.edu.hk",
    website: "https://www.lasalle.edu.hk",
    foundedYear: 1957,
    language: "english",
    curriculum: "local",
    tuitionFeeMin: 0,
    tuitionFeeMax: 0,
    studentCount: 1200,
    teacherCount: 60,
    rating: 4.8,
    linkedSchool: "喇沙書院",
    description: "喇沙小學是香港著名的天主教男子小學，以優質教育和全人發展著稱。",
    features: JSON.stringify(["STEM教育", "音樂培訓", "體育發展", "宗教教育"]),
  },
  {
    name: "瑪利諾修院學校（小學部）",
    nameEn: "Maryknoll Convent School (Primary Section)",
    type: "primary",
    category: "aided",
    gender: "girls",
    religion: "catholic",
    district: "九龍城區",
    address: "九龍窩打老道130號",
    phone: "23360611",
    email: "info@mcs.edu.hk",
    website: "https://www.mcs.edu.hk",
    foundedYear: 1925,
    language: "english",
    curriculum: "local",
    tuitionFeeMin: 0,
    tuitionFeeMax: 0,
    studentCount: 1000,
    teacherCount: 55,
    rating: 4.7,
    linkedSchool: "瑪利諾修院學校（中學部）",
    description: "瑪利諾修院學校是香港歷史悠久的天主教女子學校。",
    features: JSON.stringify(["語言培訓", "藝術教育", "品德教育", "服務學習"]),
  },
  {
    name: "協恩中學附屬小學",
    nameEn: "Heep Yunn Primary School",
    type: "primary",
    category: "aided",
    gender: "girls",
    religion: "christian",
    district: "九龍城區",
    address: "九龍農圃道1號",
    phone: "27111263",
    email: "info@hyps.edu.hk",
    website: "https://www.hyps.edu.hk",
    foundedYear: 1936,
    language: "english",
    curriculum: "local",
    tuitionFeeMin: 0,
    tuitionFeeMax: 0,
    studentCount: 900,
    teacherCount: 50,
    rating: 4.5,
    linkedSchool: "協恩中學",
    description: "協恩中學附屬小學是香港著名的基督教女子小學。",
    features: JSON.stringify(["音樂培訓", "體育發展", "領袖訓練", "服務學習"]),
  },
  // 小學 - 南區
  {
    name: "聖保羅男女中學附屬小學",
    nameEn: "St. Paul's Co-educational College Primary School",
    type: "primary",
    category: "dss",
    gender: "coed",
    religion: "christian",
    district: "南區",
    address: "香港薄扶林域多利道777號",
    phone: "25501115",
    email: "info@spccps.edu.hk",
    website: "https://www.spccps.edu.hk",
    foundedYear: 1915,
    language: "english",
    curriculum: "local",
    tuitionFeeMin: 63000,
    tuitionFeeMax: 63000,
    studentCount: 1200,
    teacherCount: 80,
    rating: 4.9,
    linkedSchool: "聖保羅男女中學",
    description: "聖保羅男女中學附屬小學是香港頂尖的直資小學，以優質教育和全人發展著稱。",
    features: JSON.stringify(["STEM教育", "音樂培訓", "體育發展", "語言培訓", "領袖訓練"]),
  },
  // 小學 - 油尖旺區
  {
    name: "拔萃女小學",
    nameEn: "Diocesan Girls' Junior School",
    type: "primary",
    category: "private",
    gender: "girls",
    religion: "christian",
    district: "油尖旺區",
    address: "九龍佐敦道1號",
    phone: "27141270",
    email: "info@dgjs.edu.hk",
    website: "https://www.dgjs.edu.hk",
    foundedYear: 1860,
    language: "english",
    curriculum: "local",
    tuitionFeeMin: 70000,
    tuitionFeeMax: 70000,
    studentCount: 1100,
    teacherCount: 70,
    rating: 4.8,
    linkedSchool: "拔萃女書院",
    description: "拔萃女小學是香港歷史最悠久的女子學校之一。",
    features: JSON.stringify(["音樂培訓", "體育發展", "藝術教育", "語言培訓"]),
  },
  // 小學 - 深水埗區
  {
    name: "英華小學",
    nameEn: "Ying Wa Primary School",
    type: "primary",
    category: "dss",
    gender: "boys",
    religion: "christian",
    district: "深水埗區",
    address: "九龍深水埗英華街3號",
    phone: "27288300",
    email: "info@yingwaps.edu.hk",
    website: "https://www.yingwaps.edu.hk",
    foundedYear: 1818,
    language: "english",
    curriculum: "local",
    tuitionFeeMin: 18000,
    tuitionFeeMax: 18000,
    studentCount: 900,
    teacherCount: 55,
    rating: 4.6,
    linkedSchool: "英華書院",
    description: "英華小學是香港歷史悠久的基督教男子學校。",
    features: JSON.stringify(["STEM教育", "音樂培訓", "體育發展", "領袖訓練"]),
  },
  // 小學 - 黃大仙區
  {
    name: "德望學校（小學部）",
    nameEn: "Good Hope School (Primary Section)",
    type: "primary",
    category: "private",
    gender: "girls",
    religion: "catholic",
    district: "黃大仙區",
    address: "九龍清水灣道303號",
    phone: "23202727",
    email: "info@ghs.edu.hk",
    website: "https://www.ghs.edu.hk",
    foundedYear: 1954,
    language: "english",
    curriculum: "local",
    tuitionFeeMin: 42000,
    tuitionFeeMax: 42000,
    studentCount: 1000,
    teacherCount: 60,
    rating: 4.6,
    linkedSchool: "德望學校",
    description: "德望學校是香港著名的天主教女子學校。",
    features: JSON.stringify(["音樂培訓", "藝術教育", "體育發展", "宗教教育"]),
  },
  // 小學 - 中西區
  {
    name: "聖公會聖彼得小學",
    nameEn: "S.K.H. St. Peter's Primary School",
    type: "primary",
    category: "aided",
    gender: "coed",
    religion: "christian",
    district: "中西區",
    address: "香港山道70及88號",
    phone: "25469325",
    email: "info@spps.edu.hk",
    website: "https://www.spps.edu.hk",
    foundedYear: 1849,
    language: "chinese",
    curriculum: "local",
    tuitionFeeMin: 0,
    tuitionFeeMax: 0,
    studentCount: 800,
    teacherCount: 45,
    rating: 4.7,
    linkedSchool: null,
    description: "聖公會聖彼得小學是香港歷史悠久的基督教小學。",
    features: JSON.stringify(["品德教育", "語言培訓", "體育發展", "服務學習"]),
  },
  // 幼稚園
  {
    name: "維多利亞幼稚園",
    nameEn: "Victoria Kindergarten",
    type: "kindergarten",
    category: "private",
    gender: "coed",
    religion: "none",
    district: "中西區",
    address: "香港堅尼地城卑路乍街56號",
    phone: "28177133",
    email: "info@victoria.edu.hk",
    website: "https://www.victoria.edu.hk",
    foundedYear: 1965,
    language: "bilingual",
    curriculum: "ib",
    tuitionFeeMin: 80000,
    tuitionFeeMax: 120000,
    studentCount: 300,
    teacherCount: 30,
    rating: 4.5,
    linkedSchool: "維多利亞（滬江維多利亞學校）",
    description: "維多利亞幼稚園是香港著名的國際幼稚園，提供IB課程。",
    features: JSON.stringify(["IB課程", "雙語教學", "探究學習", "藝術教育"]),
  },
  // 國際學校
  {
    name: "漢基國際學校",
    nameEn: "Chinese International School",
    type: "international",
    category: "international",
    gender: "coed",
    religion: "none",
    district: "東區",
    address: "香港北角寶馬山道1號",
    phone: "25106088",
    email: "info@cis.edu.hk",
    website: "https://www.cis.edu.hk",
    foundedYear: 1983,
    language: "bilingual",
    curriculum: "ib",
    tuitionFeeMin: 200000,
    tuitionFeeMax: 250000,
    studentCount: 1500,
    teacherCount: 150,
    rating: 4.7,
    linkedSchool: null,
    description: "漢基國際學校是香港頂尖的國際學校，提供完整的IB課程。",
    features: JSON.stringify(["IB課程", "雙語教學", "國際視野", "領袖訓練"]),
  },
  // 中學
  {
    name: "皇仁書院",
    nameEn: "Queen's College",
    type: "secondary",
    category: "government",
    gender: "boys",
    religion: "none",
    district: "灣仔區",
    address: "香港銅鑼灣高士威道120號",
    phone: "25761992",
    email: "info@qc.edu.hk",
    website: "https://www.qc.edu.hk",
    foundedYear: 1862,
    language: "english",
    curriculum: "local",
    tuitionFeeMin: 0,
    tuitionFeeMax: 0,
    studentCount: 1000,
    teacherCount: 70,
    rating: 4.8,
    linkedSchool: null,
    description: "皇仁書院是香港歷史最悠久的官立中學，培育無數社會精英。",
    features: JSON.stringify(["學術卓越", "體育發展", "領袖訓練", "服務學習"]),
  },
];

async function seed() {
  const connection = await createConnection(process.env.DATABASE_URL);
  
  console.log('Connected to database');
  
  for (const school of schools) {
    try {
      await connection.execute(
        `INSERT INTO schools (
          name, name_en, type, category, gender, religion, district, address,
          phone, email, website, founded_year, language, curriculum,
          tuition_fee_min, tuition_fee_max, student_count, teacher_count,
          rating, linked_school, description, features, created_at, updated_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())
        ON DUPLICATE KEY UPDATE
          name_en = VALUES(name_en),
          type = VALUES(type),
          category = VALUES(category),
          updated_at = NOW()`,
        [
          school.name, school.nameEn, school.type, school.category, school.gender,
          school.religion, school.district, school.address, school.phone, school.email,
          school.website, school.foundedYear, school.language, school.curriculum,
          school.tuitionFeeMin, school.tuitionFeeMax, school.studentCount, school.teacherCount,
          school.rating, school.linkedSchool, school.description, school.features
        ]
      );
      console.log(`Inserted: ${school.name}`);
    } catch (error) {
      console.error(`Error inserting ${school.name}:`, error.message);
    }
  }
  
  await connection.end();
  console.log('Seed completed');
}

seed().catch(console.error);
